apiVersion: v1
kind: Service
metadata:
  name: backend
spec:
  selector:
    app: backend
  ports:
  - name: backend
    port: 9091
    targetPort: 9091
  - name: backend2
    port: 9090
    targetPort: 9090
