apiVersion: apps/v1
kind: Deployment
metadata:
  name: backend
spec:
 replicas: 1
 selector:
   matchLabels:
     app: backend
 template:
   metadata:
     labels:
       app: backend
   spec:
     containers:
       - name: backend
         image: backend
         imagePullPolicy: IfNotPresent
         env:
           - name: FLASK_SERVER_PORT
             value: "9091"
           - name: MONGO_SERVER_PORT 
             value: mongo:27017
