apiVersion: apps/v1
kind: Deployment
metadata:
  name: mongo
spec:
 replicas: 1
 selector:
   matchLabels:
     run: mongo
 template:
   metadata:
     labels:
       run: mongo
   spec:
     containers:
       - name: mongo
         image: mongo
         resources: {}
status: {}