apiVersion: apps/v1
kind: Deployment
metadata:
  name: mongo
spec:
 replicas: 1
 selector:
   matchLabels:
     app: mongo
 template:
   metadata:
     labels:
       app: mongo
   spec:
     containers:
       - name: mongo
         env:
           - name: MONGO_SERVER_PORT
             value: "27017"
         image: mongo
