apiVersion: apps/v1
kind: Deployment
metadata:
  name: web
spec:
 replicas: 1
 selector:
   matchLabels:
     app: web
 template:
   metadata:
     labels:
       app: web
   spec:
     containers:
     - name: web
       image: nginx:latest
       env:
       - name: FLASK_SERVER_ADDR
         value: backend:9091
       ports:
       - containerPort: 80
       resources: {}
       volumeMounts:
       - name: nginx-config
         mountPath: /etc/nginx/nginx.conf
         subPath: nginx.conf
         readOnly: true
     volumes:
     - name: nginx-config
       configMap:
       name: nginx-config
       items:
         - key: nginx.conf
           path: nginx.conf
status: {}
