apiVersion: apps/v1
kind: Deployment
metadata:
  name: web
spec:
 replicas: 1
 selector:
   matchLabels:
     app: web
 template:
   metadata:
     labels:
       app: web
   spec:
     containers:
     - name: web
       image: nginx:latest
       args:
       - /bin/bash -c "envsubst < /tmp/nginx.conf > /etc/nginx/conf.d/default.conf && nginx -g 'daemon off;'" 
       env:
       - name: FLASK_SERVER_ADDR
         value: backend:9091
       ports:
       - containerPort: 80
       resources: {}
       volumeMounts:
       - name: nginx-config
         mountPath: /tmp/nginx.conf
         subPath: nginx.conf
     volumes:
     - name: nginx-config
       configMap:
       name: nginx-config
status: {}
